# Generated by Django 3.1.6 on 2021-02-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zolnierz',
            fields=[
                ('id_zolnierza', models.AutoField(primary_key=True, serialize=False)),
                ('imie', models.CharField(max_length=45)),
                ('nazwisko', models.CharField(max_length=45)),
                ('data_urodzenia', models.DateField()),
                ('telefon', models.CharField(max_length=15)),
                ('specjalnosc', models.CharField(max_length=90)),
                ('stanowisko_etatowe', models.CharField(max_length=90)),
                ('zameldowanie', models.TextField()),
            ],
            options={
                'db_table': 'zolnierze',
            },
        ),
    ]
